<?php
/**
 * Plugin Name: Tomatillo Design AVIF Everywhere
 * Plugin URI:  https://www.tomatillodesign.com/
 * Description: Automatically create AVIF copies of uploads, serve AVIF on front-end and admin where possible. Full library retro-conversion available.
 * Version:     1.2
 * Author:      Tomatillo Design
 * Author URI:  https://www.tomatillodesign.com/
 * License:     GPL2
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain: tomatillo-avif-everywhere
 */

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

// --- Plugin Constants ---
define( 'TOMATILLO_AVIF_VERSION', '1.2.0' );
define( 'TOMATILLO_AVIF_FILE', __FILE__ );
define( 'TOMATILLO_AVIF_DIR', plugin_dir_path( __FILE__ ) );
define( 'TOMATILLO_AVIF_URL', plugin_dir_url( __FILE__ ) );
define( 'TOMATILLO_AVIF_ASSETS_URL', TOMATILLO_AVIF_URL . 'assets/' );
define( 'TOMATILLO_AVIF_TEXT_DOMAIN', 'tomatillo-avif-everywhere' );


// --- Load Modular Includes ---
$includes = [
	'core-generation.php',
	'meta-store.php',
	'upload-hook.php',
	'batch-process.php',
	'frontend-swap.php',
	'admin-ui.php',
	'debug-tools.php',
	'helpers.php',
	'admin/scan-library.php',
	'admin/settings-page.php',
	'admin/ajax-handlers.php',
	'admin/attachment-fields.php',
	'cleanup/delete-variants-on-delete.php',
];

foreach ( $includes as $file ) {
	$path = TOMATILLO_AVIF_DIR . 'includes/' . $file;
	if ( file_exists( $path ) ) {
		require_once $path;
	}
}


add_shortcode( 'test_avif_meta', function() {
	$attachment_id = 82; // swap to real ID
	$file = get_attached_file( $attachment_id );

	if ( ! $file || ! file_exists( $file ) ) {
		return '<p>Original file not found.</p>';
	}

	$generation = tomatillo_generate_image_formats( $file );
	if ( is_wp_error( $generation ) ) {
		return '<p>Generation failed: ' . esc_html( $generation->get_error_message() ) . '</p>';
	}

	$meta_result = tomatillo_store_avif_webp_meta( $attachment_id, $generation );
	if ( is_wp_error( $meta_result ) ) {
		return '<p>Meta storage failed: ' . esc_html( $meta_result->get_error_message() ) . '</p>';
	}

	ob_start();
	echo '<h3>Stored Format URLs:</h3><ul>';
	foreach ( $meta_result as $key => $url ) {
		echo '<li><strong>' . esc_html( $key ) . ':</strong> <code>' . esc_url( $url ) . '</code></li>';
	}
	echo '</ul>';

	return ob_get_clean();
} );



add_action( 'admin_footer-plugins.php', function() {
	$plugin_slug = plugin_basename( __FILE__ );
	$plugin_folder = basename( dirname( __FILE__ ) );

	?>
	<script>
	document.addEventListener('DOMContentLoaded', function () {
		const linkId = 'deactivate-<?php echo esc_js( $plugin_folder ); ?>';
		console.log('[AVIF-SWAP] Looking for deactivate link with id:', linkId);

		const link = document.getElementById(linkId);
		if (!link) {
			console.warn('[AVIF-SWAP] Could not find deactivate link.');
			return;
		}

		link.addEventListener('click', function (e) {
			const msg = `== When You Deactivate or Delete ==

Disabling or deleting the plugin will:
- Stop automatic AVIF generation for new uploads
- Revert the Media Library and modal views to their default JPEG/PNG appearance

However, any .avif files already generated by the plugin WILL remain on your server. They are safe to leave in place, but if desired, you may manually remove them from the /wp-content/uploads/ directory.

Are you sure you want to deactivate this plugin?`;

			if (!window.confirm(msg)) {
				e.preventDefault();
				console.log('[AVIF-SWAP] Deactivation cancelled.');
			} else {
				console.log('[AVIF-SWAP] Deactivation confirmed.');
			}
		});
	});
	</script>
	<?php
});
